#SPDX-License-Identifier: MIT-0
---
# handlers file for nextcloud

- name: restart_app
  service:
    name: "{{item}}"
    state: restarted
    enabled: yes
  with_items:
    - memchached
    - httpd2

