
---
- name: Установка необходимых пакетов
  apt_rpm:
    pkg: apt-repo-tools
    state: present
    update_cache: yes
  tags: repo_custom_task

- name: Создание скелета репозитория
  file:
    path: "{{ repo_custom_path }}/{{ item[0] }}/{{ item[1] }}"
    state: directory
    mode: '0755'
  loop: "{{ repo_custom_arch | product(['base', 'RPMS.' + repo_custom_name]) | list }}"
  loop_control:
    label: "{{ item[0] }}/{{ item[1] }}"
  tags: repo_custom_task

- name: Copy generate_metadata.sh to /root/
  template:
    dest: "/root/generate_metadata.sh"
    src: "generate_metadata.sh.j2"
    owner: root
    group: root
    mode: 0755
  tags: repo_custom_task

- name: Put example custom x64 rpm to repo
  copy:
    dest: "{{repo_custom_path}}/x86_64/RPMS.{{repo_custom_name}}/{{item|basename}}"
    src: "{{ item }}"
    follow: yes
  loop: "{{ lookup('fileglob', 'files/*.rpm', wantlist=true) }}"
  tags: copy_rpm_to_custom_repo,repo_custom_task

- name: Создание задания в crontab для {{repo_custom_name}} repo
  ansible.builtin.cron:
    name: "Custom repository sync"
    minute: "{{ repo_custom_sync_period.split(' ')[0] }}"
    hour: "{{ repo_custom_sync_period.split(' ')[1] }}"
    day: "{{ repo_custom_sync_period.split(' ')[2] }}"
    month: "{{ repo_custom_sync_period.split(' ')[3] }}"
    weekday: "{{ repo_custom_sync_period.split(' ')[4] }}"
    job: "/root/generate_metadata.sh"
    user: root
  tags: repo_custom_task
